//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAVILION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employeer()
        {
            this.Rent = new HashSet<Rent>();
        }
    
        public int id_employeer { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string midllename { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string phone { get; set; }
        public string gender { get; set; }
        public byte[] foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
    }
}
