//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAVILION
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int id_rent { get; set; }
        public int id_renter { get; set; }
        public int id_tc { get; set; }
        public int id_employee { get; set; }
        public string num_pavilion { get; set; }
        public string title_tc { get; set; }
        public string status { get; set; }
        public System.DateTime start_rent { get; set; }
        public System.DateTime off_rent { get; set; }
    
        public virtual Employeer Employeer { get; set; }
        public virtual Renter Renter { get; set; }
        public virtual Pavilions Pavilions { get; set; }
    }
}
